name = "fluffy-links"
main = "src/index.js"
compatibility_date = "2025-11-17"

[[kv_namespaces]]
binding = "URLS"
id = "f347d3d279254508b4f991bf0d0f3c19"

[ai]
binding = "AI"

[version_metadata]
binding = "CF_VERSION_METADATA"

[vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1473844711910277331/fNOUnTXD8zMU_THNd07A_ql7WCKHNp69HRZd_5SdJQHfIRWc1J-soxnMc9W9FHfSLTFu"